# Pytorch basics

<center><a href="https://pytorch.org/">
    <img src="https://upload.wikimedia.org/wikipedia/commons/9/96/Pytorch_logo.png" width="300"></a></center>
    
In this first script, we see the basics of Pytorch for manipulating tensors.

Remember to check the [official documentation](https://pytorch.org/docs/stable/index.html), which is frequently used in these labs.


In [2]:
import torch
import numpy as np
from matplotlib import pyplot as plt

## Creating tensors

A [tensor](https://en.wikipedia.org/wiki/Tensor) is a multi-dimensional array (just like numpy arrays), which can store any structured numerical data. A 0D-tensor is just a scalar number, a 1D-tensor is a vector, a 2D-tensor is a matrix, a 3D-tensor is a "cube", etc.

<center><a href="https://medium.com/@anoorasfatima/10-most-common-maths-operation-with-pytorchs-tensor-70a491d8cafd">
    <img src="https://miro.medium.com/max/1308/1*8jdzMrA33Leu3j3F6A8a3w.png" width="400"></a></center>


In [ ]:
# Reminder of numpy
x = np.zeros((1, 5))  # create a 2D array (of shape 1x5) filled with 0
print(x)
x = np.ones((1, 5))  # create a 2D array (of shape 1x5) filled with 1
print(x)
x = np.array([[1, 2], [3, 4]])  # create an array with specified values
print(x)
print(x.shape, x.shape[0], x.shape[1])  # get the shape of an array
x = np.random.randn(
    4, 5
)  # create an array with numbers drawn from a standard normal distribution
print(x)

In [ ]:
# TO DO: create the same tensors in pytorch
# hint: use 'torch' instead of 'np', the functions are similar

x = torch.zeros((1, 5))  # create a 2D array (of shape 1x5) filled with 0
print("x: ", x)

x = torch.ones((1, 5))  # create a 2D array (of shape 1x5) filled with 1
print("x: ", x)

x = torch.asarray([[1, 2], [3, 4]])  # create an array with specified values
print("x: ", x)

print(x.shape, x.shape[0], x.shape[1])  # get the shape of an array

x = torch.randn(
    4, 5
)  # create an array with numbers drawn from a standard normal distribution
print("x: ", x)

In [ ]:
# Numpy Bridge: it's also possible to directly transform numpy arrays into pytorch tensor
x_np = np.ones((2, 3))
print(x_np)
x_pt = torch.from_numpy(x_np)
print(x_pt)

# And conversely:
x_np = x_pt.numpy()
print(x_np)

In [ ]:
# Another way to create a tensor filled with a given value
x = torch.zeros((1, 5))
x.fill_(20)
print(x)

In [ ]:
# With some functions, you can create an array without explicitly providing the shape (but instead use another tensor)
y = torch.randn_like(x)
print(y)
print(y.shape, x.shape)

In [ ]:
# TO DO:
# - create a tensor x0 that has the same size of x and filled with 0
x0 = torch.zeros_like(x)

# - create a tensor x1 that has the same size of x and filled with 1
x1 = torch.ones_like(x)

In [ ]:
# Create an array of numbers from 'ind_beg' to 'ind_end' with an increment of 'inc_step'
ind_beg = 3
ind_end = 10
inc_step = 2
x = torch.arange(ind_beg, ind_end, inc_step)
print(x)

# Default values are 'ind_beg=0' and 'inc_step=1':
x = torch.arange(ind_end)
print(x)

## Basic loops


In [ ]:
# The most simple 'for' loop
for i in range(10):
    print(i)

In [ ]:
# alternatively, you can create a tensor containing the indices over which iterating
list_iter = torch.arange(10)
for i in list_iter:
    print(i)

In [ ]:
# You can also directly iterate over the elements of a 1D-tensor (or list)
my_list = torch.randn(10)
print(my_list)
for x in my_list:
    print(x)

In [ ]:
# If you use 'enumerate', you can keep track of the index
for i, x in enumerate(my_list):
    print(i, x)

In [ ]:
# If the object to iterate is a multivariate tensor, then it will iterate over the first dimension
# For instance, if we iterate over a tensor of size [10, 16, 16], it will produce 10 tensors of size [16,16]

mytensor = torch.randn(10, 16, 16)
for x in mytensor:
    print(x.shape)
    plt.figure()
    plt.imshow(x)
    plt.show()

## Basic operations


In [ ]:
x = torch.ones((1, 5))
x.fill_(5)
y = torch.ones((1, 5))
y.fill_(3)

# Addition, subtraction, multiplication, division, and power
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x**y)

In [ ]:
# Pytorch has some built-in basic math functions (exp, sin, cos...) that can be applied element-wise to a tensor
x = torch.randn(2, 3)
y = torch.exp(x)
print(y)

In [ ]:
# TO DO: plot the function y=sin(x)
# - create a tensor x which ranges from -5 to 5 with a step increment of 0.1
x = torch.arange(-5, 5, 0.1)

# - compute y=sin(x) (use the torch.sin function)
y = torch.sin(x)

# - plot it using plt.plot(x, y)
plt.plot(x, y)


In [ ]:
# TO DO: plot a noisy sinusoid
# - create a noise tensor called 'noise' with the same shape as y (use torch.randn_like)
noise = torch.randn_like(y)

# - create a scalar amount_noise which control the amount of noise (set it at 0.1 for instance)
amount_noise = 0.02

# - compute z, which is the sum of y and the noise tensor * the amount of noise
z = y + noise * amount_noise

# - plot z as a function of x
plt.plot(x, z)


In [ ]:
# Slicing (same as in numpy)
x = torch.randn(5, 6)
print(x[:3])  # slice over the first dimension
print(x[:, :3])  # slice over the second dimension
print(x[:3, :3])  # slice over both dimensions

In [ ]:
# Useful functions are min, max, argmin and argmax
x = torch.rand(1, 5)
print(x)
print(x.min(), x.max(), x.argmin(), x.argmax())

# It's also easy to sort a tensor with ascending values
x_sorted, ind_sort = x.sort()
print(x_sorted, ind_sort)

In [ ]:
# TO DO: find the minimum of a quadratic function
# - create a tensor x which ranges from -4 to 4 with a step of 0.01
x = torch.arange(-4, 4, 0.01)

# - compute y = x^2 - 5x + 3
y = x**2 - 5 * x + 3

# - plot y as a function of x
plt.plot(x, y)

# - compute the minimum value of y and print it
print(torch.min(y))

# - find the index 'ind_min' corresponding to this minimum (hint: use the 'argmin' function)
ind_min = torch.argmin(y)
print(ind_min)

# - compute the value of x corresponding to the minimum: x[ind_min]
x_min = x[ind_min]
print(x_min)


## Tensor types

In Pytorch there are several data types, which are listed in the [documentation](https://pytorch.org/docs/stable/tensors.html).


In [ ]:
x = torch.rand(1, 10)
print(x)

# Display the type using the 'dtype' attribute
# By default, it should be float32
print(x.dtype)

In [ ]:
# Change the type using the 'type' method
x = x.type(torch.float16)
print(x.dtype)

# Convert it to integer
x = x.type(torch.int16)
print(x.dtype)
print(x)

In [ ]:
# You can specify the type when creating a tensor
x = torch.tensor(3, dtype=torch.int)
print(x)

In [34]:
# Check if it's a float
x = torch.tensor(3, dtype=torch.int)
print(x.is_floating_point())

pi = torch.tensor(3.14159)
print(pi, pi.is_floating_point(), pi.dtype)

False
tensor(3.1416) True torch.float32


## Reshaping


In [35]:
x = torch.randn(8, 5)
print(x.shape)

# Transposition: use either 'x.t()' or 'x.transpose(dims)' where 'dims' specifies the new dimensions order
y = x.transpose(1, 0)
print(y.shape)

z = x.t()
print(z.shape)

torch.Size([8, 5])
torch.Size([5, 8])
torch.Size([5, 8])


In [36]:
# Reshape: reorganize the tensor with the specified output dimensions (similar as 'numpy.reshape')
x = torch.randn(8, 5)
y = x.reshape(10, 4)
print(x.shape, y.shape)

# You can only specify one dimension and mark the other with '-1', and it will autocomplete consistently
z = x.reshape(-1, 10)
print(z.shape)
z = x.reshape(2, -1)
print(z.shape)


torch.Size([8, 5]) torch.Size([10, 4])
torch.Size([4, 10])
torch.Size([2, 20])


In [37]:
# View: similar as 'reshape', but only creates a view over the tensor: if the original data is changed, then the viewed tensors also changes
x = torch.zeros(8, 5)
y = x.view(10, 4)
print(y)

x.fill_(1)
print(y)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


## Squeeze and unsqueeze

It's important to understand that there is a difference between a tensor of shape `[a, b]` and a tensor of shape `[a, b, 1]`: even though the same data can be stored in both, the second one as an extra dimension (the third one) that can be useful, e.g., if you want to assemble tensors together in a bigger object.

For instance, an image with height `a` and width `b` can be seen as a 2D-tensor of shape `[a, b]`. But you can also view it as a single frame in a video, then it's a 3D-tensor of shape `[a, b, 1]`, and the whole video made up with `c` frames would be a 3D-tensor of shape `[a, b, c]`.

From a given tensor, you can add an extra dimension (with shape 1) using the `unsqueeze` method. Conversely, you can remove a dimension with shape 1 using the `squeeze` method.


In [3]:
# Example of squeeze: remove all dimensions with shape 1
x = torch.zeros(2, 1, 5, 1)
print(x.shape)
y = x.squeeze()
print(y.shape)

torch.Size([2, 1, 5, 1])
torch.Size([2, 5])


In [4]:
# Conversely, 'unsqueeze' allows you to expand a tensor by adding a new dimension, whose location must be specified
x = torch.zeros(2, 5)
print(x.shape)
y = x.unsqueeze(dim=0)
print(y.shape)
z = x.unsqueeze(dim=2)
print(z.shape)

torch.Size([2, 5])
torch.Size([1, 2, 5])
torch.Size([2, 5, 1])


## Assembling tensors


In [5]:
# Concatenate: useful to concatenate tensors along a specified (existing) dimension
# Works with any tensors, provided that the dimensions over which you don't concatenate are consistent
x1 = torch.rand(15, 64, 64)
x2 = torch.rand(50, 64, 64)
X_concat = torch.cat((x1, x2), dim=0)
print(X_concat.shape)

x1 = torch.rand(10, 217)
x2 = torch.rand(10, 489)
X_concat = torch.cat((x1, x2), dim=1)
print(X_concat.shape)

x1 = torch.rand(10, 217, 12)
x2 = torch.rand(10, 217, 14)
X_concat = torch.cat((x1, x2), dim=2)
print(X_concat.shape)

torch.Size([65, 64, 64])
torch.Size([10, 706])
torch.Size([10, 217, 26])


In [7]:
# TO DO :
# - create two tensors of shape 16x16 with random values.
x = torch.rand(16, 16)
y = torch.rand(16, 16)

# - unsqueeze them to create a new dimension (of size 1)
x = x.unsqueeze(dim=0)
y = y.unsqueeze(dim=0)

# - concatenate them into a single tensor of size (2, 16, 16)
X_concat = torch.cat((x, y), dim=0)
print(X_concat.shape)

# hint: first 'unsqueeze' the tensors to create a new dimension, and then 'cat' over this dimension


torch.Size([2, 16, 16])


In [8]:
# Stack: unlike 'cat', 'stack' concatenates the tensors along a new dimension (the inputs tensors must have the same shape)
x = torch.ones(3, 10)
y = torch.ones(3, 10)
print(x.shape, y.shape)

z_stack = torch.stack((x, y), dim=0)
print(z_stack.shape)

# Check the difference with 'cat'
z_cat = torch.cat((x, y), dim=0)
print(z_cat.shape)

torch.Size([3, 10]) torch.Size([3, 10])
torch.Size([2, 3, 10])
torch.Size([6, 10])


In [9]:
# It's possible to stack over any dimension, so it will create a tensor accordingly
z_stack = torch.stack((x, y), dim=1)
print(z_stack.shape)

z_stack = torch.stack((x, y), dim=2)
print(z_stack.shape)

torch.Size([3, 2, 10])
torch.Size([3, 10, 2])


In [11]:
# TO DO : same exercice as before but using stack (should be simpler)
# - create two tensors of shape 16x16 with random values.
x = torch.rand(16, 16)
y = torch.rand(16, 16)

# - stack them to create a new dimension (of size 2)
z_stack = torch.stack((x, y), dim=0)
print(z_stack.shape)

torch.Size([2, 16, 16])


## Save and load files


In [13]:
# Reminder in numpy
x_np = np.ones((2, 3))
np_filepath = "x_np.npy"
np.save(np_filepath, x_np)
x_np_load = np.load(np_filepath)
print(x_np_load)

# In pytorch, it's very similar
x_tensor = torch.from_numpy(x_np)
tensor_filepath = "x_tensor.pt"
torch.save(x_tensor, tensor_filepath)
x_tensor_load = torch.load(tensor_filepath)
print(x_tensor_load)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


## Devices

Finally, let's note that there are two types of _devices_ in Pytorch: `cpu` and `cuda`. By default, every tensor's device is `cpu`, which means that all computation is performed on the CPU. However, when training big models and handling big datasets (as in deep learning), it's more convenient to use a graphic card (GPU) for the computation. To do that, we just need to tell Pytorch that the data / tensors / models should be copied on a `cuda` device.
This is mostly for your general knowledge: we won't use GPU computation in these labs.

**Note**: If you didn't install pytorch with CUDA, you should get an error if you try to copy a tensor to `cuda`. That's fine.


In [14]:
# You can check if a GPU is available (and how many)
print("Cuda available:", torch.cuda.is_available())
print("Number of GPUs:", torch.cuda.device_count())

# By default, any tensor will be on a 'cpu' device
x = torch.rand(1, 10)
print(x.device)

# You can change it using the 'to' method
# Doing this is only possible if you have installed CUDA with Pytorch, so you might get an error here.
x = x.to("cuda")
print(x.device)

Cuda available: True
Number of GPUs: 1
cpu
cuda:0
